### ISSUE TITLE
Documents behind feature flags is not rendered

### ISSUE THREAD

**Issue by andylokandy** [fast/logforth#45]
https://docs.rs/logforth/0.9.1/logforth/index.html

**Comment by tisonkun** [comment]
Yeah .. It seems we should properly configure cfg docs or cfg docsrs things.

I'm not quite familiar with them yet >_<

**Comment by andylokandy** [comment]
AFAIN, there is a way to enforce docs.rs to enable all features...

**Comment by tisonkun** [comment]
https://github.com/fast/logforth/blob/8fd1f347422186123a086a42fad70d542f846aac/Cargo.toml#L30-L32

@andylokandy I did it here. So IIRC all features' doc should be present actually.

The missing part is the "only available if feature xxx on", like:
<img width="988" alt="image" src="https://github.com/user-attachments/assets/f5d1b835-1ad3-4023-b5fa-3d7f7f94f225">
