### ISSUE TITLE
PatternLayout

### ISSUE THREAD

**Issue by tisonkun** [fast/logforth#7]
Something like https://logging.apache.org/log4j/2.x/manual/layouts.html#PatternLayout.

But we should not reimplement a tribal format. Instead, we can try to leverage tera, mini_jinja or other template libraries.

**Comment by JimChenWYU** [comment]
Maybe we need something like https://github.com/estk/log4rs/blob/main/src/encode/pattern/mod.rs ?

**Comment by tisonkun** [comment]
I'm afraid that it's over complex and yet another handmade pattern language. I'd prefer to leverage existing template lib as listed above.

**Comment by JimChenWYU** [comment]
emm, I can't understand the difference between customLayout.

**Comment by tisonkun** [comment]
Oops .. That it.

So the requirement is actually resolved :D
